import { MigrationInterface, QueryRunner } from 'typeorm';

export class seedsAuthors1632325690067 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
		insert into "author" (name, "createdAt", "updatedAt") values ('Elsbeth Crotty', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Edwina Neat', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Timofei Beville', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Gabriel Tongs', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Ardis Trewartha', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Teodora Pods', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Rosamond Rennock', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Salmon Skryne', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Vinnie Bevington', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Malena Fillary', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Gusella Rosenstiel', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Estele Peppett', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Dud Musgrave', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Ludwig Bohea', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Ilse Estick', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Elizabet Perillo', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Gael Englefield', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Sergio Fortnam', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Hilliard Gladding', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Hynda Temlett', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Myrlene Gaskoin', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Kinnie Downgate', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Woodrow Bedo', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Valene Penner', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Nonna Rubbert', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Vale Staveley', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Trevor Rannie', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Libbey McManamon', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Hilarius Reagan', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Barbette Hathaway', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Chet Thewys', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Denna Dunford', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Charissa Moan', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Shaina Snellman', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Carlynn Dooher', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Salli Niland', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Rolf Wike', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Adda de Banke', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Colin Aubry', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Bennie Kolushev', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Giustino Balentyne', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Reiko Sacher', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Benyamin Warner', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Gene McCromley', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Deirdre Stockley', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Roarke Eynald', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Queenie Kusick', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Miles Spaule', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Renate Younghusband', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Fons Dwane', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Daffie Loosely', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Chilton O''Nion', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Isa Caulder', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Stormie Vose', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Griff Anwyl', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Cymbre Lesek', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Betsy Goldby', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Tirrell Grinaway', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Shandra Clewett', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Reynard Espinoza', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Shannah Guyonneau', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Nickie Alldis', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Sonnie Cristea', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Marcelle Forrington', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Aguste Stepney', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Taite Brettoner', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Larina Farnin', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Peggy Shasnan', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Kris Levene', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Natala Minifie', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Nicko Longmate', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Randee Pordal', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Stillmann Capaldi', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Sheryl Garric', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Gerard Roscoe', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Allard Billingham', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Lenora McGurn', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Phelia Carrane', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Chelsea Ducarne', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Dionysus Kille', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Hagen Kittoe', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Carmela Sherer', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Devin Tocqueville', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Spenser Wrenn', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Kasey Longson', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Skipp Baumert', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Conrado Pennells', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Shirlene Chesson', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Evelyn Pauler', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Grier Woolmore', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Antonietta Seabrook', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Babbie Twelves', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Tad Ghiraldi', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Clarabelle Higbin', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Phil Stavers', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Petrina Howieson', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Rennie Bathersby', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Calla O''Glessane', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Doralin Fishly', 'now()', 'now()');
insert into "author" (name, "createdAt", "updatedAt") values ('Yvonne Crayke', 'now()', 'now()');	
		`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
			drop table "author";
			drop table "book";
		`);
  }
}
